### ISSUE TITLE
*.go というファイル名は小文字で始めるかつ一単語で表すのが良いとされていそう

### ISSUE THREAD

**Issue by pankona** [takano-hi/golang-web-server-sample#1]
Refs: https://github.com/golang/go/issues/36060

Naming convention として明らかにどこかに書かれている風ではなさそうですが (ちなみに、そういうときはだいたい標準ライブラリの法則に従うとハズレがありません)、ソースファイル名は「小文字で始める」かつ「できれば一単語で表す」のが良いとされていそうです。一部大文字始まりのファイルがあるようなのでちょっと気になりました。

良い
- router.go
- setup.go
- greatfeature.go

悪い
- Router.go
- Setup.go
- great_feature.go

## なぜ一単語？

もとい、アンスコで単語を区切らないほうがいい、という論説です。

ファイル名を長くしたいとき、アンダースコアか何かで区切りたくなる場合があるだろうと思いますが、アンダースコアの利用は注意が必要です。Go のコンパイラはアンダースコアで区切られた単語をビルドスイッチとして認識する場合があるからです。

たとえば hoge_linux.go、hoge_android.go、hoge_darwin.go などです。特定のビルド環境でのみビルド対象になるファイルとして認識されます。hoge_midwhite.go のようなファイル名が将来に渡ってビルドスイッチとして使われる可能性はとても低いかもしれず、そういう意味ではある程度気を使えばそこまで神経質にならなくてもいいかもしれませんが、しかしゼロパーセントではないだろうと思うならば、やはり「アンスコでファイル名を分割する」のは避けておくと無難だろうと思います。
ちなみに、ハイフンなどで区切るのはたぶん安全です。けど、あんまり好きじゃない人が多いかもしれない？

**Comment by takano-hi** [comment]
@pankona ありがとうございます 🙏🙏🙏 ビルドスイッチ知らなかったです…！
こちらで対応しました！

- https://github.com/midwhite/golang-web-server-sample/pull/2
